### ISSUE TITLE
Replicated Link in Learning Galaxy

### ISSUE THREAD

**Issue by lydiayliu** [kellrott/galaxy-tooldev-docs#20]
In 3.5.0 under **Video Resources**, the two links for "Managing Histories" and "Reproducible research and Galaxy" are the same and link to the video "Managing Histories".

If you are looking to link ""Reproducible research and Galaxy" to the video "Reproducible research and the 90/10 rule: Improving the ratio of light script to dark script matter in your Galaxy", the link is https://vimeo.com/74885862

**Comment by kellrott** [comment]
This should be fixed in https://github.com/kellrott/galaxy-tooldev-docs/commit/b76b3a570874c2bcd421223ca78f87431e7d36f4

**Comment by lydiayliu** [comment]
This is not fixed properly. I have commented under the commit.
